services:
  - type: web
    name: your-project-name
    env: node
    repo: https://github.com/Plbyatt86/recipe-app
    branch: main
    buildCommand: npm install
    startCommand: npm run build && npm run serve
    region: us
    envVars:
      - key: KEY
        value: value
