services:
  - type: web
    name: recipe-app
    env: node
    repo: https://github.com/Plbyatt86/recipe-app
    branch: main
    buildCommand: npm install && npm run build
    startCommand: npx serve -s build
    region: us
    envVars:
      - key: KEY
        value: value
